module.exports = {
    sounds: {
        cat: [
            'soundbank://soundlibrary/animals/amzn_sfx_cat_angry_meow_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_angry_meow_1x_02',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_angry_screech_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_long_meow_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_meow_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_meow_1x_02',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_purr_01',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_purr_02',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_purr_03',
            'soundbank://soundlibrary/animals/amzn_sfx_cat_purr_meow_01',
        ],
        bird: [
            'soundbank://soundlibrary/animals/amzn_sfx_bird_chickadee_chirp_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bird_chickadee_chirps_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bird_forest_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bird_forest_02',
            'soundbank://soundlibrary/animals/amzn_sfx_bird_forest_short_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bird_robin_chirp_1x_01',
        ],
        bear: [
            'soundbank://soundlibrary/animals/amzn_sfx_bear_groan_roar_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bear_roar_grumble_01',
            'soundbank://soundlibrary/animals/amzn_sfx_bear_roar_small_01',
        ],
        chicken: ['soundbank://soundlibrary/animals/amzn_sfx_chicken_cluck_01'],
        crow: [
            'soundbank://soundlibrary/animals/amzn_sfx_crow_caw_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_crow_caw_1x_02',
        ],
        dog: [
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_1x_02',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_1x_03',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_2x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_2x_02',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_2x_03',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_growl_01',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_growl_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_med_woof_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_dog_small_bark_2x_01',
        ],
        elephant: [
            'soundbank://soundlibrary/animals/amzn_sfx_elephant_01',
            'soundbank://soundlibrary/animals/amzn_sfx_elephant_02',
            'soundbank://soundlibrary/animals/amzn_sfx_elephant_03',
            'soundbank://soundlibrary/animals/amzn_sfx_elephant_04',
            'soundbank://soundlibrary/animals/amzn_sfx_elephant_05',
        ],
        horse: [
            'soundbank://soundlibrary/animals/amzn_sfx_horse_gallop_4x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_gallop_4x_02',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_gallop_4x_03',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_huff_whinny_01',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_neigh_01',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_neigh_low_01',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_whinny_01',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_whinny_02',
            'soundbank://soundlibrary/animals/amzn_sfx_horse_whinny_03',
        ],
        lion: [
            'soundbank://soundlibrary/animals/amzn_sfx_lion_roar_01',
            'soundbank://soundlibrary/animals/amzn_sfx_lion_roar_02',
            'soundbank://soundlibrary/animals/amzn_sfx_lion_roar_03',
        ],
        monkey: [
            'soundbank://soundlibrary/animals/amzn_sfx_monkey_calls_3x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_monkey_chimp_01',
            'soundbank://soundlibrary/animals/amzn_sfx_monkeys_chatter_01',
        ],
        rat: [
            'soundbank://soundlibrary/animals/amzn_sfx_rat_squeak_2x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_rat_squeaks_01',
        ],
        raven: [
            'soundbank://soundlibrary/animals/amzn_sfx_raven_caw_1x_01',
            'soundbank://soundlibrary/animals/amzn_sfx_raven_caw_2x_01',
        ],
        rooster: [
            'soundbank://soundlibrary/animals/amzn_sfx_rooster_crow_01',
            'soundbank://soundlibrary/animals/amzn_sfx_rooster_crow_02',
        ],
        sheep: [
            'soundbank://soundlibrary/animals/amzn_sfx_sheep_baa_01',
            'soundbank://soundlibrary/animals/amzn_sfx_sheep_bleat_01',
            'soundbank://soundlibrary/animals/amzn_sfx_sheep_bleat_02',
            'soundbank://soundlibrary/animals/amzn_sfx_sheep_bleat_03',
        ],
        turkey: ['soundbank://soundlibrary/animals/amzn_sfx_turkey_gobbling_01'],
        wolf: [
            'soundbank://soundlibrary/animals/amzn_sfx_wolf_howl_01',
            'soundbank://soundlibrary/animals/amzn_sfx_wolf_howl_02',
            'soundbank://soundlibrary/animals/amzn_sfx_wolf_howl_03',
            'soundbank://soundlibrary/animals/amzn_sfx_wolf_young_howl_01',
        ],
    },
};
